site_name: XOR_
# site_description: 'XOR_ Knowledge Base'
site_url: https://learn.01111000011011110111001001011111.com/
# https://github.com/584F525F/584F525F.github.io/
# https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/#with-colors-docsstylesheetsextracss
# https://github.com/squidfunk/mkdocs-material/tree/master/material/templates/.icons

theme:
  name: material
  # custom_dir: overrides
  icon: 
    # repo: fontawesome/brands/github-alt
    logo: fontawesome/brands/mandalorian
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  favicon: assets/icons/mandalorian-white.png

  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/lighthouse-on
        name: Switch to dark mode
      primary: black
      accent: orange

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/lighthouse
        name: Switch to light mode
      primary: black
      accent: orange

  features:
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tabs.link
    - navigation.tracking
    - navigation.top
    - navigation.tabs
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.path
    - search.highlight
    - search.suggest
    - search.share
    - toc.follow
    # - toc.integrate # this disables the right-side table of content but shows it under the right-side table of content
    # - navigation.tabs.sticky #on scroll down it remains visible on top

markdown_extensions:
  - tables
  - attr_list
  - admonition
  - def_list
  - pymdownx.details
  - pymdownx.blocks.details
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tasklist:
      custom_checkbox: true

# repo_url: https://github.com/584F525F
edit_uri: edit/master/

copyright: Copyright © 2024 01111000011011110111001001011111.com

# copyright: >
#   Copyright © 2024 01111000011011110111001001011111.com –
#   <a href="#__consent">Change cookie settings</a>

extra:
  generator: true
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/584F525F/
    - icon: fontawesome/solid/paper-plane
      link: mailto:contact@01111000011011110111001001011111.com
  # consent:
  #   actions:
  #     - accept
  #     - reject
  #     - manage

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - open-in-new-tab
  # - privacy
  # - tags
  - git-revision-date-localized
  # - social
  # - optimize #https://squidfunk.github.io/mkdocs-material/plugins/optimize
  # - typeset: #icons on left-side table of content
  #     enabled: true
  #https://squidfunk.github.io/mkdocs-material/reference/images/
  - glightbox:
      effect: zoom
      width: 100%
      height: auto
      background: gray
      zoomable: true
      draggable: true
      auto_caption: false
      caption_position: bottom
      shadow: true
      slide_effect: slide
      loop: false
      touchNavigation: true

nav:
  - Home: home.html
  - Cyber Offensive:
    - 'Summary': Cyber_Offensive.md
    - '':
      - 'File Transfers':
        - 'FTP': Cyber_Offensive/File_Transfers/FTP.md
        - 'ftpd': Cyber_Offensive/File_Transfers/ftpd.md
        - 'scp': Cyber_Offensive/File_Transfers/scp.md
        - 'SMB': Cyber_Offensive/File_Transfers/SMB.md
        - 'Telnet': Cyber_Offensive/File_Transfers/Telnet.md
        - 'windows_certutil': Cyber_Offensive/File_Transfers/windows_certutil.md
        - 'windows cscript': Cyber_Offensive/File_Transfers/windows_cscript.md
        - 'Windows mshta wmic regsvr32': Cyber_Offensive/File_Transfers/Windows_mshta_wmic_regsvr32.md
      - 'Initial Enumeration': Cyber_Offensive/Initial_Enumeration/Initial_Enumeration.md
      - 'Password Attacks, Cracking':
        - 'Argon2 cracker': Cyber_Offensive/Password_Attacks,_Cracking_&_Decoding/Argon2_cracker.md
        - 'Cracking Files': Cyber_Offensive/Password_Attacks,_Cracking_&_Decoding/Cracking_Files.md
        - 'Decoding': Cyber_Offensive/Password_Attacks,_Cracking_&_Decoding/Decoding.md
        - 'Hashcat': Cyber_Offensive/Password_Attacks,_Cracking_&_Decoding/Hashcat.md
        - 'Hydra': Cyber_Offensive/Password_Attacks,_Cracking_&_Decoding/Hydra.md
        - 'Medusa': Cyber_Offensive/Password_Attacks,_Cracking_&_Decoding/Medusa.md
        - 'Ncrack': Cyber_Offensive/Password_Attacks,_Cracking_&_Decoding/Ncrack.md
        - 'Passing the hash': Cyber_Offensive/Password_Attacks,_Cracking_&_Decoding/Passing_the_hash.md
        - 'Wordlists': Cyber_Offensive/Password_Attacks,_Cracking_&_Decoding/Wordlists.md
        - 'Basic Usage': Cyber_Offensive/Password_Attacks,_Cracking_&_Decoding/JohnTheRipper/Basic_Usage.md
        - 'Cracking modes': Cyber_Offensive/Password_Attacks,_Cracking_&_Decoding/JohnTheRipper/Cracking_modes.md
        - 'Misc & Tricks': Cyber_Offensive/Password_Attacks,_Cracking_&_Decoding/JohnTheRipper/Misc_&_Tricks.md
        - 'Rules': Cyber_Offensive/Password_Attacks,_Cracking_&_Decoding/JohnTheRipper/Rules.md
        - 'Wordlists & Incremental': Cyber_Offensive/Password_Attacks,_Cracking_&_Decoding/JohnTheRipper/Wordlists_&_Incremental.md
      - 'Privilege Escalation':
        - 'Linux Privilege Escalation': Cyber_Offensive/Privilege_Escalation/Linux_Privilege_Escalation/Linux_Privilege_Escalation.md
        - 'Windows Privilege Escalation': Cyber_Offensive/Privilege_Escalation/Windows_Privilege_Escalation/Windows_Privilege_Escalation.md
      - 'Reconnaissance':
        - 'DNSdumpster': Cyber_Offensive/Recon/DNSdumpster.md
        - 'recon': Cyber_Offensive/Recon/recon.md
        - 'shodan.io': Cyber_Offensive/Recon/shodan.io.md
      - 'Remote connection & execution':
        - 'atexec.py': Cyber_Offensive/Remote_connection_&_execution/atexec.py.md
        - 'dcomexec.py': Cyber_Offensive/Remote_connection_&_execution/dcomexec.py.md
        - 'evil-winrm': Cyber_Offensive/Remote_connection_&_execution/evil-winrm.md
        - 'psexec.py': Cyber_Offensive/Remote_connection_&_execution/psexec.py.md
        - 'Remote connection & execution': Cyber_Offensive/Remote_connection_&_execution/Remote_connection_&_execution.md
        - 'Reverse Shell': Cyber_Offensive/Remote_connection_&_execution/Reverse_Shell.md
        - 'smbexec.py': Cyber_Offensive/Remote_connection_&_execution/smbexec.py.md
        - 'winrm': Cyber_Offensive/Remote_connection_&_execution/winrm.md
        - 'wmiexec.py': Cyber_Offensive/Remote_connection_&_execution/wmiexec.py.md
      - 'Reverse Shell': Cyber_Offensive/Reverse_shell/r.md
      - 'Services':
        - 'FTP': Cyber_Offensive/Services/FTP.md
        - 'IMAP': Cyber_Offensive/Services/IMAP.md
        - 'MSSQL': Cyber_Offensive/Services/MSSQL.md
        - 'POP3': Cyber_Offensive/Services/POP3.md
        - 'SMTP': Cyber_Offensive/Services/SMTP.md
        - 'SAMBA _ SMB': Cyber_Offensive/Services/Samba_SMB/SAMBA_-_SMB.md
        - 'SMB Client': Cyber_Offensive/Services/Samba_SMB/SMB_Client.md
        - 'Tools': Cyber_Offensive/Services/Samba_SMB/Tools.md
      - 'Web':
        - 'RFI-LFI_File_Inclusion': Cyber_Offensive/Web/RFI-LFI_File_Inclusion.md
        - 'SQL_Injection': Cyber_Offensive/Web/SQL_Injection.md
        - 'SSRF': Cyber_Offensive/Web/SSRF.md
        - 'XSS': Cyber_Offensive/Web/XSS_(Cross-Site_Scripting).md
        - 'Command_Injection':
          - 'IDOR': Cyber_Offensive/Web/Command_Injection/IDOR.md
        - 'Enumeration & Content Discovery':
          - 'Content Discovery Tools':
            - 'Authentication_Bypass_-_User enumeration': Cyber_Offensive/Web/Enumeration_&_Content_Discovery/Authentication_Bypass_-_User enumeration/Authentication_Bypass_-_User enumeration.md
            - 'Cansina': Cyber_Offensive/Web/Enumeration_&_Content_Discovery/Directory_Busting/Content_Discovery_Tools/Cansina.md
            - 'Chameleon': Cyber_Offensive/Web/Enumeration_&_Content_Discovery/Directory_Busting/Content_Discovery_Tools/Chameleon.md
            - 'froxbuster': Cyber_Offensive/Web/Enumeration_&_Content_Discovery/Directory_Busting/Content_Discovery_Tools/froxbuster.md
            - 'fuff': Cyber_Offensive/Web/Enumeration_&_Content_Discovery/Directory_Busting/Content_Discovery_Tools/fuff.md
            - 'General_Content_Discovery': Cyber_Offensive/Web/Enumeration_&_Content_Discovery/Directory_Busting/Content_Discovery_Tools/General_Content_Discovery.md
            - 'gobuster': Cyber_Offensive/Web/Enumeration_&_Content_Discovery/Directory_Busting/Content_Discovery_Tools/gobuster.md
            - 'Katana': Cyber_Offensive/Web/Enumeration_&_Content_Discovery/Directory_Busting/Content_Discovery_Tools/Katana.md
            - 'Kiterunner': Cyber_Offensive/Web/Enumeration_&_Content_Discovery/Directory_Busting/Content_Discovery_Tools/Kiterunner.md
            - 'Wfuzz': Cyber_Offensive/Web/Enumeration_&_Content_Discovery/Directory_Busting/Content_Discovery_Tools/Wfuzz.md
          - 'File and Directory Enumeration':
            - 'Dictionaries': Cyber_Offensive/Web/Enumeration_&_Content_Discovery/Directory_Busting/File_and_Directory_Enumeration/Dictionaries.md
            - 'dirb': Cyber_Offensive/Web/Enumeration_&_Content_Discovery/Directory_Busting/File_and_Directory_Enumeration/dirb.md
            - 'dirbuster': Cyber_Offensive/Web/Enumeration_&_Content_Discovery/Directory_Busting/File_and_Directory_Enumeration/dirbuster.md
            - 'dirsearch': Cyber_Offensive/Web/Enumeration_&_Content_Discovery/Directory_Busting/File_and_Directory_Enumeration/dirsearch.md
  - Knowledge Base:
    - 'Summary': knowledge_base.md
    - '': 
      - 'Network':
        - 'ARP' : Knowledge_Base/Network/ARP.md
        - 'DNS' : Knowledge_Base/Network/DNS.md
        - 'DHCP' : Knowledge_Base/Network/dhcp.md
        - 'Email' :
          - 'POP3' : Knowledge_Base/Network/Email/POP3.md
          - 'SMTP' : Knowledge_Base/Network/Email/SMTP.md
          - 'IGMP' : Knowledge_Base/Network/IGMP.md
          - 'DKIM DomainKeys Identified Mail' : Knowledge_Base/Network/Email/DKIM_DomainKeys_Identified_Mail.md
          - 'DMRAC Domain-based Message Authentication Reporting and Conformance' : Knowledge_Base/Network/Email/DMRAC_Domain-based_Message_Authentication_Reporting_and_Conformance.md
          - 'SPF Sender Policy Framework' : Knowledge_Base/Network/Email/SPF_Sender_Policy_Framework.md
        - 'Packet Capture' : 
          - 'Wireshark': 
            - 'Filters' : Knowledge_Base/Network/Packet_Capture/Wireshark/Filters.md
            - 'Profiles' : Knowledge_Base/Network/Packet_Capture/Wireshark/Profiles.md
          - 'TCP dump' : Knowledge_Base/Network/Packet_Capture/TCP_Dump.md
        - 'Radius' : Knowledge_Base/Network/Radius.md
        - 'SNMP' : Knowledge_Base/Network/SNMP.md
        - 'Subnetting' : Knowledge_Base/Network/Subnetting.md
        - 'VPN' : Knowledge_Base/Network/VPN.md
      - 'OS':
        - 'Windows':
          - 'Applications' : Knowledge_Base/OS/Windows/applications.md
          - 'Commands':
            - 'PowerShell file & folder operation' : Knowledge_Base/OS/Windows/Commands/PowerShell_file_operation.md
            - 'Removing Edge Browser' : Knowledge_Base/OS/Windows/Commands/Removing_Edge_Browser.md
            - 'Routes' : Knowledge_Base/OS/Windows/Commands/routes.md
            - 'Windows Start-up' : Knowledge_Base/OS/Windows/Commands/Windows_Start-up.md
            - 'WSL Windows Subsystem Linux' : Knowledge_Base/OS/Windows/Commands/WSL_Windows_Subsystem_Linux.md
          - 'Troubleshooting' :
            - 'ERR SSL VERSION OR CIPHER MISMATCH' : Knowledge_Base/OS/Windows/Troubleshooting/ERR_SSL_VERSION_OR_CIPHER_MISMATCH.md
        - 'Linux':
          - 'Debian':
            - 'Package Management' : 
              - 'apt' : Knowledge_Base/OS/Linux/Debian/Package_Management/apt.md
              - 'dpkg' : Knowledge_Base/OS/Linux/Debian/Package_Management/dpkg.md
              - 'other' : Knowledge_Base/OS/Linux/Debian/Package_Management/other.md
            - 'Kali' : 
              - 'Issues fixes' : Knowledge_Base/OS/Linux/Debian/Kali/Issues_fixes.md
              - 'kali setup' : Knowledge_Base/OS/Linux/Debian/Kali/kali_setup.md
              - 'kali setup' : Knowledge_Base/OS/Linux/Debian/Kali/Proxychains.md
              - 'SSH Server' : Knowledge_Base/OS/Linux/Debian/Kali/SSH_Server.md
              - 'VNC over SSH' : Knowledge_Base/OS/Linux/Debian/Kali/VNC_over_SSH.md
              - 'Wireless Adapter' : Knowledge_Base/OS/Linux/Debian/Kali/Wireless_Adapter.md
          - 'Arch' : 
            - 'virt manager' : Knowledge_Base/OS/Linux/Arch/virt-manager.md
      - 'Coding':
        - 'Ansible' : Knowledge_Base/Coding/Ansible.md
        - 'C | C++' : Knowledge_Base/Coding/C_C++.md
        - 'C#' : Knowledge_Base/Coding/C#.md
        - 'Github | Git' : Knowledge_Base/Coding/Github_Git.md
        - 'Python' : Knowledge_Base/Coding/Python.md
        - 'YAML' : Knowledge_Base/Coding/YAML.md
        - 'Linux Bash' : Knowledge_Base/Coding/Linux_Bash.md
        - 'Windows Powershell' : Knowledge_Base/Coding/Windows_Powershell.md
      - 'Home Lab' : 
        - 'Docker' : Knowledge_Base/Home_Lab/Docker.md
        - 'Kasm Workspaces' : Knowledge_Base/Home_Lab/Kasm_Workspaces.md
        - 'pfSense' : Knowledge_Base/Home_Lab/pfSense.md
        - 'Portainer Docker' : Knowledge_Base/Home_Lab/Portainer_Docker.md
        - 'Wazuh SEIM' : Knowledge_Base/Home_Lab/Wazuh_SEIM.md
  - About: About.md
