site_name: BitwiseOperator XOR_
# site_description: 'XOR_ Knowledge Base'
# site_url: https://xor.bitwiseoperator.net/home.html
# https://github.com/584F525F/584F525F.github.io/
# https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/#with-colors-docsstylesheetsextracss
# https://github.com/squidfunk/mkdocs-material/tree/master/material/templates/.icons

theme:
  name: material
  # custom_dir: overrides
  icon: 
    # repo: fontawesome/brands/github-alt
    logo: fontawesome/brands/mandalorian
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  favicon: assets/icons/mandalorian-white.png

  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/lighthouse-on
        name: Switch to dark mode
      primary: black
      accent: orange

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/lighthouse
        name: Switch to light mode
      primary: black
      accent: orange

  features:
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - navigation.tracking
    - navigation.path
    - navigation.top
    - navigation.tabs
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.sections
    - search.highlight
    - search.suggest
    - search.share
    - toc.follow
    # - toc.integrate # this disables the right-side table of content but shows it under the right-side table of content
    # - navigation.tabs.sticky #on scroll down it remains visible on top

markdown_extensions:
  - tables
  - attr_list
  - admonition
  - def_list
  - pymdownx.details
  - pymdownx.blocks.details
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tasklist:
      custom_checkbox: true

# repo_url: https://github.com/584F525F
edit_uri: edit/master/

copyright: Copyright © 2024 bitwiseoperator.net

# copyright: >
#   Copyright © 2024 bitwiseoperator.net
#   <a href="#__consent">Change cookie settings</a>

extra:
  generator: true
  homepage: https://xor.bitwiseoperator.net/home.html
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/584F525F/
    - icon: fontawesome/solid/paper-plane
      link: mailto:contact@bitwiseoperator.net
  # consent:
  #   actions:
  #     - accept
  #     - reject
  #     - manage

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  # - mkpdfs
  - open-in-new-tab
  # - mkdocs-pdf
  # - privacy
  # - tags
  - git-revision-date-localized
  # - social
  # - optimize #https://squidfunk.github.io/mkdocs-material/plugins/optimize
  # - typeset: #icons on left-side table of content
  #     enabled: true
  #https://squidfunk.github.io/mkdocs-material/reference/images/
  - glightbox:
      effect: zoom
      width: 100%
      height: auto
      background: gray
      zoomable: true
      draggable: true
      auto_caption: false
      caption_position: bottom
      shadow: true
      slide_effect: slide
      loop: false
      touchNavigation: true
nav:
  - Home: home.html
  - Knowledge Base:
    - 'Summary': Knowledge_Base.md
    - '':
      - 'Coding':
        - 'Ansible': Knowledge_Base/Coding/Ansible.md
        - 'C#': Knowledge_Base/Coding/C#.md
        - 'C C++': Knowledge_Base/Coding/C_C++.md
        - 'Github Git': Knowledge_Base/Coding/Github_Git.md
        - 'Linux Bash': Knowledge_Base/Coding/Linux_Bash.md
        - 'Python': Knowledge_Base/Coding/Python.md
        - 'Windows Powershell': Knowledge_Base/Coding/Windows_Powershell.md
        - 'YAML': Knowledge_Base/Coding/YAML.md
      - 'Home Lab':
        - 'Docker': Knowledge_Base/Home_Lab/Docker.md
        - 'Kasm Workspaces': Knowledge_Base/Home_Lab/Kasm_Workspaces.md
        - 'pfSense': Knowledge_Base/Home_Lab/pfSense.md
        - 'Portainer Docker': Knowledge_Base/Home_Lab/Portainer_Docker.md
        - 'Wazuh SEIM': Knowledge_Base/Home_Lab/Wazuh_SEIM.md
      - 'Network':
        - 'ARP': Knowledge_Base/Network/ARP.md
        - 'Cabling Fiber': Knowledge_Base/Network/Cabling_Fiber.md
        - 'Cabling Fiber SFPs': Knowledge_Base/Network/Cabling_Fiber_SFPs.md
        - 'dhcp': Knowledge_Base/Network/dhcp.md
        - 'DNS': Knowledge_Base/Network/DNS.md
        - 'IGMP': Knowledge_Base/Network/IGMP.md
        - 'Network Fundamentals': Knowledge_Base/Network/Network_Fundamentals.md
        - 'Radius': Knowledge_Base/Network/Radius.md
        - 'SNMP': Knowledge_Base/Network/SNMP.md
        - 'Subnetting': Knowledge_Base/Network/Subnetting.md
        - 'VPN': Knowledge_Base/Network/VPN.md
        - 'Email':
          - 'DKIM DomainKeys Identified Mail': Knowledge_Base/Network/Email/DKIM_DomainKeys_Identified_Mail.md
          - 'DMRAC Domain-based Message Authentication Reporting and Conformance': Knowledge_Base/Network/Email/DMRAC_Domain-based_Message_Authentication_Reporting_and_Conformance.md
          - 'POP3': Knowledge_Base/Network/Email/POP3.md
          - 'SMTP': Knowledge_Base/Network/Email/SMTP.md
          - 'SPF Sender Policy Framework': Knowledge_Base/Network/Email/SPF_Sender_Policy_Framework.md
        - 'Packet Capture':
          - 'TCP Dump': Knowledge_Base/Network/Packet_Capture/TCP_Dump.md
          - 'Wireshark':
            - 'Wireshark Profiles': Knowledge_Base/Network/Packet_Capture/Wireshark/Wireshark_Profiles.md
            - 'Wireshark Filters': Knowledge_Base/Network/Packet_Capture/Wireshark/Wireshark_Filters.md
        - 'Vendor':
          - 'Aruba HPE':
            - 'Aruba Central Instant Cluster':
              - 'Aruba Central and Instant Upgrade Procedure': Knowledge_Base/Network/Vendor/Aruba_HPE/Aruba_Central_Instant_Cluster/Aruba_Central_and_Instant_Upgrade_Procedure.md
              - 'Aruba Central AP Configuration Sync issues': Knowledge_Base/Network/Vendor/Aruba_HPE/Aruba_Central_Instant_Cluster/Aruba_Central_AP_Configuration_Sync_issues.md
              - 'Aruba MTU': Knowledge_Base/Network/Vendor/Aruba_HPE/Aruba_Central_Instant_Cluster/Aruba_MTU.md
            - 'Switches':
              - 'Aruba Central Switch enable CLI': Knowledge_Base/Network/Vendor/Aruba_HPE/Switches/Aruba_Central_Switch_enable_CLI.md
              - 'Aruba HPE SFPs': Knowledge_Base/Network/Vendor/Aruba_HPE/Switches/Aruba_HPE_SFPs.md
          - 'Cisco':
            - 'CISCO WLC Handshake Failure': Knowledge_Base/Network/Vendor/Cisco/CISCO_WLC_Handshake_Failure.md
          - 'Juniper':
            - 'SRX':
              - 'Juniper Add VLAN Ethernet Switching irb': Knowledge_Base/Network/Vendor/Juniper/SRX/Juniper_Add_VLAN_Ethernet_Switching_irb.md
              - 'Juniper JNCIA study notes': Knowledge_Base/Network/Vendor/Juniper/SRX/Juniper_JNCIA_study_notes.md
              - 'Juniper SRX  WARNING BOOTED BACKUP': Knowledge_Base/Network/Vendor/Juniper/SRX/Juniper_SRX_WARNING_BOOTED_BACKUP.md
              - 'Juniper SRX Add VLAN Ethernet Switching VLAN': Knowledge_Base/Network/Vendor/Juniper/SRX/Juniper_SRX_Add_VLAN_Ethernet_Switching_VLAN.md
              - 'Juniper SRX Configuration rescue and Auto recovery': Knowledge_Base/Network/Vendor/Juniper/SRX/Juniper_SRX_Configuration_rescue_and_Auto_recovery.md
              - 'Juniper SRX dhcp-service subsystem is not responding': Knowledge_Base/Network/Vendor/Juniper/SRX/Juniper_SRX_dhcp-service_subsystem_is_not_responding.md
              - 'Juniper SRX firmware upgrade': Knowledge_Base/Network/Vendor/Juniper/SRX/Juniper_SRX_firmware_upgrade.md
              - 'Juniper SRX flow': Knowledge_Base/Network/Vendor/Juniper/SRX/Juniper_SRX_flow.md
              - 'Juniper SRX FTP CLI': Knowledge_Base/Network/Vendor/Juniper/SRX/Juniper_SRX_FTP_CLI.md
              - 'Juniper SRX Loader Recovery': Knowledge_Base/Network/Vendor/Juniper/SRX/Juniper_SRX_Loader_Recovery.md
              - 'Juniper SRX NAT 1TO1': Knowledge_Base/Network/Vendor/Juniper/SRX/Juniper_SRX_NAT_1TO1.md
              - 'Juniper SRX NAT Destination': Knowledge_Base/Network/Vendor/Juniper/SRX/Juniper_SRX_NAT_Destination.md
              - 'Juniper SRX NAT Source': Knowledge_Base/Network/Vendor/Juniper/SRX/Juniper_SRX_NAT_Source.md
              - 'Juniper SRX NAT Troubleshooting': Knowledge_Base/Network/Vendor/Juniper/SRX/Juniper_SRX_NAT_Troubleshooting.md
              - 'Juniper SRX packet capture pcap': Knowledge_Base/Network/Vendor/Juniper/SRX/Juniper_SRX_packet_capture_pcap.md
              - 'Juniper SRX redundancy cluster failover troubleshooting': Knowledge_Base/Network/Vendor/Juniper/SRX/Juniper_SRX_redundancy_cluster_failover_troubleshooting.md
              - 'Juniper srx troubleshooting': Knowledge_Base/Network/Vendor/Juniper/SRX/Juniper_srx_troubleshooting.md
              - 'Juniper SRX Troubleshoot restart IPSEC VPN': Knowledge_Base/Network/Vendor/Juniper/SRX/Juniper_SRX_Troubleshoot_restart_IPSEC_VPN.md
              - 'Juniper SRX WARNING REMOTE HOST IDENTIFICATION HAS CHANGED': Knowledge_Base/Network/Vendor/Juniper/SRX/Juniper_SRX_WARNING_REMOTE_HOST_IDENTIFICATION_HAS_CHANGED.md
          - 'Meraki':
            - 'Meraki SFP': Knowledge_Base/Network/Vendor/Meraki/Meraki_SFP.md
          - 'Ruckus':
            - 'Access Points':
              - 'AP-CLI general-commands': Knowledge_Base/Network/Vendor/Ruckus/Access_Points/AP-CLI_general-commands.md
              - 'Ruckus SmartZone SZ AP CLI SETUP Support Config Flow': Knowledge_Base/Network/Vendor/Ruckus/Access_Points/Ruckus_SmartZone_SZ_AP_CLI_SETUP_Support_Config_Flow.md
              - 'Ruckus SZ AP Access Point Firmware Recovery CLI': Knowledge_Base/Network/Vendor/Ruckus/Access_Points/Ruckus_SZ_AP_Access_Point_Firmware_Recovery_CLI.md
              - 'Ruckus WAP TX Power EIRP': Knowledge_Base/Network/Vendor/Ruckus/Access_Points/Ruckus_WAP_TX_Power_EIRP.md
            - 'Switches':
              - 'ALL SFP RUCKUS Optics': Knowledge_Base/Network/Vendor/Ruckus/Switches/ALL_SFP_RUCKUS_Optics.md
              - 'Brocade ICX console settings': Knowledge_Base/Network/Vendor/Ruckus/Switches/Brocade_ICX_console_settings.md
              - 'Brocade ICX Switches Firmware upgrade with USB': Knowledge_Base/Network/Vendor/Ruckus/Switches/Brocade_ICX_Switches_Firmware_upgrade_with_USB.md
              - 'Ruckus SFP Brocade ICX-7250-ds': Knowledge_Base/Network/Vendor/Ruckus/Switches/Ruckus_SFP_Brocade_ICX-7250-ds.md
            - 'WLC':
              - 'SZ SmartZone':
                - 'Ruckus SmartZone SZ CLI General Cluster Upgrade and backup': Knowledge_Base/Network/Vendor/Ruckus/WLC/SZ_SmartZone/Ruckus_SmartZone_SZ_CLI_General_Cluster_Upgrade_and_backup.md
                - 'SZ AP Management MGMT Control Data Plane Ports': Knowledge_Base/Network/Vendor/Ruckus/WLC/SZ_SmartZone/SZ_AP_Management_MGMT_Control_Data_Plane_Ports.md
                - 'SZ upgrade': Knowledge_Base/Network/Vendor/Ruckus/WLC/SZ_SmartZone/SZ_upgrade.md
              - 'Unleashed':
              - 'ZD ZoneDirector':
                - 'Ruckus ZoneDirector ZD CLI': Knowledge_Base/Network/Vendor/Ruckus/WLC/ZD_ZoneDirector/Ruckus_ZoneDirector_ZD_CLI.md
                - 'ZD Channelization': Knowledge_Base/Network/Vendor/Ruckus/WLC/ZD_ZoneDirector/ZD_Channelization.md
  - About: About.md
