site_name: BitwiseOperator XOR_
# site_description: 'XOR_ Knowledge Base'
# site_url: https://xor.bitwiseoperator.net/home.html
# https://github.com/584F525F/584F525F.github.io/
# https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/#with-colors-docsstylesheetsextracss
# https://github.com/squidfunk/mkdocs-material/tree/master/material/templates/.icons

theme:
  name: material
  # custom_dir: overrides
  icon: 
    # repo: fontawesome/brands/github-alt
    logo: fontawesome/brands/mandalorian
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  favicon: assets/icons/mandalorian-white.png

  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/lighthouse-on
        name: Switch to dark mode
      primary: black
      accent: orange

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/lighthouse
        name: Switch to light mode
      primary: black
      accent: orange

  features:
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - navigation.tracking
    - navigation.path
    - navigation.top
    - navigation.tabs
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.sections
    - search.highlight
    - search.suggest
    - search.share
    - toc.follow
    # - toc.integrate # this disables the right-side table of content but shows it under the right-side table of content
    # - navigation.tabs.sticky #on scroll down it remains visible on top

markdown_extensions:
  - tables
  - attr_list
  - admonition
  - def_list
  - pymdownx.details
  - pymdownx.blocks.details
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tasklist:
      custom_checkbox: true

# repo_url: https://github.com/584F525F
edit_uri: edit/master/

copyright: Copyright © 2024 bitwiseoperator.net

# copyright: >
#   Copyright © 2024 bitwiseoperator.net
#   <a href="#__consent">Change cookie settings</a>

extra:
  generator: true
  homepage: https://xor.bitwiseoperator.net/home.html
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/584F525F/
    - icon: fontawesome/solid/paper-plane
      link: mailto:contact@bitwiseoperator.net
  # consent:
  #   actions:
  #     - accept
  #     - reject
  #     - manage

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  # - mkpdfs
  - open-in-new-tab
  # - mkdocs-pdf
  # - privacy
  # - tags
  - git-revision-date-localized
  # - social
  # - optimize #https://squidfunk.github.io/mkdocs-material/plugins/optimize
  # - typeset: #icons on left-side table of content
  #     enabled: true
  #https://squidfunk.github.io/mkdocs-material/reference/images/
  - glightbox:
      effect: zoom
      width: 100%
      height: auto
      background: gray
      zoomable: true
      draggable: true
      auto_caption: false
      caption_position: bottom
      shadow: true
      slide_effect: slide
      loop: false
      touchNavigation: true
nav:
  - Home: home.html
  - About: About.md
