site_name: XOR_
site_description: 'XOR_'
site_url: https://github.com/584F525F/584F525F.github.io/

theme:
  name: material
  icon:
    repo: fontawesome/brands/github-alt
    logo: fontawesome/brands/github
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  favicon: fontawesome/brands/github-alt

extra:
  tags:
    <tag>: material/test-tube

  palette:
    - scheme: default
      toggle:
        icon: material/lighthouse-on
        name: Switch to dark mode
      primary: darkpurple
      accent: orange
    - scheme: slate
      toggle:
        icon: material/lighthouse
        name: Switch to light mode
      primary: darkpurple
      accent: orange

  features:
      - content.code.copy
      - navigation.tracking
      - navigation.top
      - content.code.select
      - navigation.path
      - content.tabs.link
      - navigation.tabs
      #- navigation.tabs.sticky #on scroll down it remains visible on top

extra_css:
    - custom.css

markdown_extensions:
  - tables
  - attr_list
  - admonition
  - def_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tasklist:
      custom_checkbox: true

repo_url: https://github.com/584F525F/584F525F.github.io
edit_uri: edit/master/

plugins:
  - search
  - tags
  - git-revision-date-localized
  - social
  #- optimize #https://squidfunk.github.io/mkdocs-material/plugins/optimize