authors:
  <author>:
    name: BitwiseOperator
    description: Author
    avatar: https://xor.bitwiseoperator.net/assets/icons/xor.png
    # slug: url           # Author profile slug
    # url: url            # Author website URL
